// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frtgupmcdckvnmabitrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydGd1cG1jZGNrdm5tYWJpdHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODM5NjQsImV4cCI6MjA1OTE1OTk2NH0.OF2pzjfKEllecYVgs24Q1IdlXk8IEfLF-l9nFYLE0TU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);